version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
        auth:
          username: $USERNAME
          password: $PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Activate Environement
          command: |
            python3 -m venv ~/.venv
            source ~/.venv/bin/activate
      - run:
          name: Install Hadolint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
      - run: 
          name: Install Dependencies
          command: |
            make install
      - run:
          name: Run lint
          command: |
            make lint

workflows:
  default:
    jobs:
      - build