version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
        auth:
          username: $USERNAME
          password: $PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            make setup
      - run: 
          name: Install Dependencies
          command: |
            make install
      - run:
          name: Run lint
          command: |
            make lint

workflows:
  default:
    jobs:
      - build